### ISSUE TITLE
Help from stackoverflow issue :)

### ISSUE THREAD

**Issue by bertrandg** [wallrj/sshwh#2]
Hi @wallrj,

Sorry to poke you there but that's the only way I found to contact you because I know stackoverflow is not always triggering notifications for a comment! :)

I come from this stackoverflow [issue](https://stackoverflow.com/questions/29953531/how-to-save-websocket-frames-in-chrome) where you exposed a really interesting way to access all websocket frames from chrome devTools: `BrowserSDK.networkLog.requests()[x]._frames`

But sadly, I can't make it work, I got an error:
**Uncaught TypeError: Cannot read property 'requests' of undefined**

Can you tell me more how you did that and you chrome version please?

Again sorry for the inconvenience!

**Comment by wallrj** [comment]
Hey :-) I just replied on the original SO page. It looks like you now have to use the `SDK` object rather than `BrowserSDK`. I found this through a bit of trial and error....I don't have much understanding of these APIs, so there might be a better way.
